### ISSUE TITLE
Add Resources Open Sources

### ISSUE THREAD

**Issue by JuanPabloDiaz** [JuanPabloDiaz/freeForGeeks#24]
## [Open Source](https://opensource.com/resources/projects-and-applications)

- [x] #49 - 
- [x] #50 - [Top 3 open source business intelligence and reporting tools](https://opensource.com/business/14/6/three-open-source-business-tools)
- [x] #51 - [Top 5 open source alternatives to Trello](https://opensource.com/business/15/8/5-open-source-alternatives-trello)
- [x] #52 - [Top 5 open source alternatives to Gmail](https://opensource.com/life/15/9/open-source-alternatives-gmail)
- [x] #53 - [Top 4 open source command-line email clients](https://opensource.com/life/15/8/top-4-open-source-command-line-email-clients)
- [x] #54 - [Top 7 open source tools and free resources for writing](https://opensource.com/life/14/5/seven-open-source-tools-writing)
- [x] #55 - [Top 10 open source alternatives to Minecraft](https://opensource.com/life/15/9/open-source-alternatives-minecraft)
- [x] #56 - [Top 4 open source tools for diagramming in Fedora](https://opensource.com/life/14/6/tools-diagramming-fedora)
- [x] #57 - [Top 3 open source tools for creating presentations](https://opensource.com/life/14/7/3-open-source-tools-make-your-presentations-pop)
- [x] #58 - [Top 3 open source content management systems](https://opensource.com/business/14/6/open-source-cms-joomla-wordpress-drupal)
- [x] #59 - [Top 4 open source ERP systems](https://opensource.com/resources/top-4-open-source-erp-systems)
- [ ] #60 - [Top 4 open source LDAP implementations](https://opensource.com/business/14/5/top-4-open-source-ldap-implementations)
- [x] #61 - [Top 3 open source alternatives to Google Analytics](https://opensource.com/business/14/10/top-3-open-source-alternatives-google-analytics)
- [x] #62 - [Top 5 open source customer relationship management tools](https://opensource.com/business/14/7/top-5-open-source-crm-tools)
- [x] #63 - [Top 3 open source scanning utilities](https://opensource.com/life/14/8/3-tools-scanners-linux-desktop)
- [x] #64 - [Top 4 open source text editors](https://opensource.com/life/13/7/4-text-editors-linux)
- [x] #65 - [Top 8 open source data visualization tools](https://opensource.com/life/15/6/eight-open-source-data-visualization-tools)
- [x] #66 - [Top 5 open source tools for taming text](https://opensource.com/business/15/7/five-open-source-nlp-tools)

**Comment by megelon** [comment]
##Add biome

**Comment by JuanPabloDiaz** [comment]
done
