### ISSUE TITLE
[Add] Roadmap

### ISSUE THREAD

**Issue by JuanPabloDiaz** [JuanPabloDiaz/freeForGeeks#69]
### Site URL

https://roadmap.sh/

### Description of the Resource(s)

Developer Roadmaps
roadmap.sh is a community effort to create roadmaps, guides and other educational content to help guide developers in picking up a path and guide their learnings.

### Category

Career Development

### Sub Category

learn to code

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/juanPabloDiaz/freeForGeeks/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
